sudo: required
services:
    - docker

before_install:
    - docker build -t rambej0201/docker-base-react -f Dockerfile.dev .
script:
    - docker run -e CI=true rambej0201/docker-base-react npm run test
language: generic